repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - .prettierignore
    - docs/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-zealgt_logo_light.png
    - docs/images/nf-core-zealgt_logo_light.png
    - docs/images/nf-core-zealgt_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-zealgt_logo_light.png
    - docs/images/nf-core-zealgt_logo_light.png
    - docs/images/nf-core-zealgt_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/igenomes.config
  readme:
    - nextflow_badge
    - nfcore_template_badge
  included_configs: false

template:
  org: sawers-rellan-labs
  name: zealgt
  description: 'ZEAL genotyping: raw reads to genotypes, stopping at one CRAM per
    sample'
  author: Fausto Rodriguez Zapata
  version: 0.1.0dev
  force: true
  outdir: tpl2
  skip_features:
    - github_badges
    - igenomes
    - nf_core_configs
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - email
    - rocrate
  is_nfcore: false
